name: apmc-billing-cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build server
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: authentication with dockerHub
        run: echo "${{secrets.DOCKERHUB_PASSWORD}}"| docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: build and push docker image
        run: |
          IMAGE_NAME=docker.io/vithsutratechnologies/apmc-billing-app-backend:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    name: deploy docker-image to Cloud Instance
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: create .env file
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "ADDRESS=${{secrets.ADDRESS}}" >> .env
          echo "SERVER_MODE=${{secrets.SERVER_MODE}}" >> .env

      - name: setup deployment in Cloud Instance
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: "${{secrets.CLOUD_INSTANCE_HOST}}"
          username: "${{secrets.CLOUD_INSTANCE_USERNAME}}"
          key: "${{secrets.CLOUD_INSTANCE_SSH_PRIVATE_KEY}}"
          script: |
            echo "connected to vm"
            mkdir -p ~/billing-app/billing-app-deployment
            mkdir -p ~/billing-app/uploads/logos
      - name: upload .env to vm
        run: |
          echo "${{secrets.CLOUD_INSTANCE_SSH_PRIVATE_KEY}}" > ssh_key
          chmod 600 ssh_key
          scp -o StrictHostKeyChecking=no -i ssh_key .env ${{ secrets.CLOUD_INSTANCE_USERNAME }}@${{ secrets.CLOUD_INSTANCE_HOST }}:~/billing-app/billing-app-deployment/.env

      - name: deploy docker image into Cloud Instance
        uses: appleboy/ssh-action@v0.1.10
        with:
           host: "${{ secrets.CLOUD_INSTANCE_HOST }}"
           username: "${{ secrets.CLOUD_INSTANCE_USERNAME }}"
           key: "${{ secrets.CLOUD_INSTANCE_SSH_PRIVATE_KEY }}"
           script: |
            IMAGE_NAME=docker.io/vithsutratechnologies/apmc-billing-app-backend:latest
            docker pull $IMAGE_NAME
            docker images | grep "<none>" | awk '{print $3}' | xargs -r docker rmi -f
            docker ps | grep apmc-billing-app-backend | awk '{print $1}' | xargs -I {} docker kill {}
            docker ps -a | grep apmc-billing-app-backend | awk '{print $1}' | xargs -I  {} docker rm {}
            docker run -d -p 8081:8080 --name apmc-billing-app-backend --env-file ~/billing-app/billing-app-deployment/.env -v "~/billing-app/uploads/logos:/app/uploads/logos" $IMAGE_NAME






